# Generated by Django 4.1.4 on 2023-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MP3Audio',
            fields=[
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('youtube_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'MP3Audio',
            },
        ),
    ]
