# Generated by Django 4.1.4 on 2023-01-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_convert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp3audio',
            name='abr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
